title: OpenRAP
email: info@sunbird.org
description: "OpenRAP "
environment: production
permalink: /:categories/:SubCategories/:title/
safe: false
defaults:
-
  scope:
    path: "docs"
  values:
    layout: "docs-detail"
    showSidebar: "false"
    allowSearch: "false"
    categoryOrder: 99
-
  scope:
    path: "docs/developer"
  values:
    categories: 
      - 'You are Developer'
    categoriesDesc: 'You develpers description'
    CategoryOrder: 1
-
  scope:
    path: "docs/facilitator"
  values:
    categories: 
      - 'You are Facilitator'
    categoriesDesc: 'You facilitators description'
    CategoryOrder: 2
-
  scope:
    path: "docs/developer/subcategory-1"
  values:
    SubCategories:
       - 'Sub Category 1'
    SubCategoryOrder: 1
-
  scope:
    path: "docs/developer/subcategory-2"
  values:
    SubCategories:
        - 'Sub Category 2'
    SubCategoryOrder: 2

-
  scope:
    path: "docs/facilitator/subcategory-3"
  values:
    SubCategories:
      - 'Sub Category 3'
    SubCategoryOrder: 1
-
  scope:
    path: "docs/facilitator/subcategory-4"
  values:
    SubCategories:
      - 'Sub Category 4'
    SubCategoryOrder: 2

-
  scope:
    path: "docs/facilitator/subcategory-5"
  values:
    SubCategories:
        - 'Sub Category 5'
    SubCategoryOrder: 3

-
  scope:
    path: "docs/facilitator/subcategory-6"
  values:
    SubCategories:
        - 'Sub Category 6'
    SubCategoryOrder: 3
-
  scope:
    path: "docs/facilitator/subcategory-7"
  values:
    SubCategories:
        - 'Sub Category 7'
    SubCategoryOrder: 3

showSearch: true
exclude:
- vendor
- .gitignore
- README.md
- ingredients
- staging
- docs/*/ingredients
- docs/*/*.sh
- docs/*/version.yaml
- .sh

sass:
    sass_dir: css
 
